imports:
    - { resource: config_dev.yml }

services:
    swiftmailer.mailer.mailer: '@swiftmailer.mailer'
    swiftmailer.mailer.mandrill: '@swiftmailer.mailer'

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true
    logging: true
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:
        type: file
        path: "%kernel.cache_dir%/spool"
